### ISSUE TITLE
Add UI for building subsets

### ISSUE THREAD

**Issue by cdmgtri** [niemopen/niem-toolbox#10]
Create a user interface to allow a user to build a subset out of content from other models.

**User gets started**

- [ ] User creates a new subset
- [ ] User uploads an existing CMF file
- [ ] User uploads a SSGT wantlist
- [ ] User uploads a zip file with XML schemas
- [ ] User documents name, description, and version number

**User builds subset with add, edit, and delete operations**

- [ ] Add button with dropdown if item is not in subset
  - [ ] Dropdown has options for common cardinality constraints
  - [ ] Popup with potential types if property is not added into a type
- [ ] Edit button with dropdown if item is in subset
  - [ ] Change cardinality
  - [ ] Delete from subset
  - [ ] Go to customized item settings

**Subset panel**

- [ ] Property list
- [ ] Property list filter
- [ ] Type list
- [ ] Type list filter
- [ ] Display flat lists
- [ ] Display hierarchical lists
- [ ] Displays QA issue indicators

**Customized item settings**

- [ ] User creates alias for property name
- [ ] User creates custom constraints for data properties
- [ ] User sets custom cardinality
- [ ] User sets custom nillable value
- [ ] niemopen/niem-api#17
  - *Also supports property as content, reference, or either*

**Subset settings**

- [ ] User sets default cardinality
- [ ] User sets default nillable value
- [ ] User sets default simpleNIEM options
  - [ ] niemopen/niem-api#13
  - [ ] niemopen/niem-api#14
  - [ ] niemopen/niem-api#15
  - [ ] User subsets `structures` content

**Subset QA**

- [ ] Tool checks if abstract elements have substitutions
- [ ] Tool checks if types are being used (has property of that type or is a base for another type)
- [ ] Tool checks for properties that are not contained within a type

**Other**

- [ ] Tool saves last-modified date
- [ ] Tool saves qa status and results
- [ ] Tool tracks default settings for all subsets
- [ ] Tool tracks custom project settings for specific subset
- [ ] Tool displays lists of all saved subsets
- [ ] Tool has confirmation guard before clearing a subset currently in progress
- [ ] Tool uses Local Storage to persist current subset identifiers across browser sessions

**API interactions**

- [ ] Tool transforms minimal CMF to full CMF
- [ ] Tool runs CMF though API's simpleNIEM transformation
- [ ] Tool transforms CMF to user-selected output format

**Results**

- [ ] Pass: User downloads subset
- [ ] Fail: Tool displays error message if subset cannot be generated
